name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.5.4
  flutter_facebook_auth: ^7.1.2
  camera: ^0.11.0
  permission_handler: ^11.0.0
  google_mlkit_face_detection: ^0.13.0
  tflite_flutter: ^0.11.0 # For running the AI model
  image: ^4.5.0 # For cropping the face image
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter_native_splash:
  color: "#42a5f5" # A nice Medical Blue color
  image: "assets/app_icon.png" # Reuse your icon
  android_12:
    image: "assets/app_icon.png"
    color: "#42a5f5"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/emotions_model.tflite
    - assets/labels.txt
    - assets/emotions_model2.tflite
    - assets/emotions_model_sajal.tflite
    - assets/google_logo.png
